export const CATEGORY_LABELS: Record<string, { lt: string; en: string; icon: string }> = {
  "poultry":           { lt: "Paukštiena",                    en: "Poultry",               icon: "🍗" },
  "beef":              { lt: "Jautiena",                       en: "Beef",                  icon: "🥩" },
  "pork":              { lt: "Kiauliena",                      en: "Pork",                  icon: "🥓" },
  "lamb":              { lt: "Aviena",                         en: "Lamb",                  icon: "🐑" },
  "minced-meat":       { lt: "Faršas",                         en: "Minced Meat",           icon: "🫙" },
  "deli-meat":         { lt: "Mėsos gaminiai",                 en: "Deli Meat & Sausages",  icon: "🌭" },
  "fish-seafood":      { lt: "Žuvis ir jūros gėrybės",        en: "Fish & Seafood",        icon: "🐟" },
  "milk":              { lt: "Pienas",                         en: "Milk",                  icon: "🥛" },
  "cheese":            { lt: "Sūris",                          en: "Cheese",                icon: "🧀" },
  "yogurt":            { lt: "Jogurtas",                       en: "Yogurt",                icon: "🍶" },
  "butter-cream":      { lt: "Sviestas ir grietinė",           en: "Butter & Cream",        icon: "🧈" },
  "cottage-cheese":    { lt: "Varškė",                         en: "Cottage Cheese & Curd", icon: "🍮" },
  "eggs":              { lt: "Kiaušiniai",                     en: "Eggs",                  icon: "🥚" },
  "bread":             { lt: "Duona",                          en: "Bread",                 icon: "🍞" },
  "bakery":            { lt: "Kepiniai",                       en: "Bakery & Pastry",       icon: "🥐" },
  "fruits":            { lt: "Vaisiai",                        en: "Fruits",                icon: "🍎" },
  "vegetables":        { lt: "Daržovės",                       en: "Vegetables",            icon: "🥕" },
  "salads-herbs":      { lt: "Salotos ir žalumynai",           en: "Salads & Herbs",        icon: "🥗" },
  "mushrooms":         { lt: "Grybai",                         en: "Mushrooms",             icon: "🍄" },
  "frozen-food":       { lt: "Šaldyti produktai",              en: "Frozen Food",           icon: "🧊" },
  "rice-grains":       { lt: "Ryžiai ir kruopos",              en: "Rice & Grains",         icon: "🍚" },
  "pasta":             { lt: "Makaronai",                      en: "Pasta & Noodles",       icon: "🍝" },
  "flour-baking":      { lt: "Miltai ir kepimo reikmenys",     en: "Flour & Baking",        icon: "🫓" },
  "oil-vinegar":       { lt: "Aliejus ir actas",               en: "Oil & Vinegar",         icon: "🫙" },
  "canned-food":       { lt: "Konservai",                      en: "Canned Food",           icon: "🥫" },
  "sauces-condiments": { lt: "Padažai ir prieskoniai",         en: "Sauces & Condiments",   icon: "🍯" },
  "snacks":            { lt: "Užkandžiai",                     en: "Snacks",                icon: "🍿" },
  "sweets-chocolate":  { lt: "Saldumynai",                     en: "Sweets & Chocolate",    icon: "🍫" },
  "cereals":           { lt: "Dribsniai ir granola",           en: "Cereals & Granola",     icon: "🥣" },
  "honey-jam":         { lt: "Medus ir džemas",                en: "Honey & Jam",           icon: "🍯" },
  "tea":               { lt: "Arbata",                         en: "Tea",                   icon: "🍵" },
  "coffee":            { lt: "Kava",                           en: "Coffee",                icon: "☕" },
  "juice":             { lt: "Sultys",                         en: "Juice",                 icon: "🧃" },
  "water":             { lt: "Vanduo",                         en: "Water",                 icon: "💧" },
  "soda-soft-drinks":  { lt: "Gaivieji gėrimai",               en: "Soft Drinks",           icon: "🥤" },
  "beer":              { lt: "Alus",                           en: "Beer",                  icon: "🍺" },
  "wine":              { lt: "Vynas",                          en: "Wine",                  icon: "🍷" },
  "spirits":           { lt: "Stiprieji alkoholiniai gėrimai", en: "Spirits",               icon: "🥃" },
  "baby-food":         { lt: "Kūdikių maistas",                en: "Baby Food",             icon: "🍼" },
  "pet-food":          { lt: "Gyvūnų maistas",                 en: "Pet Food",              icon: "🐾" },
  "cleaning":          { lt: "Valymo priemonės",               en: "Cleaning Products",     icon: "🧹" },
  "laundry":           { lt: "Skalbimo priemonės",             en: "Laundry",               icon: "🧺" },
  "paper-products":    { lt: "Popieriniai gaminiai",           en: "Paper Products",        icon: "🧻" },
  "personal-care":     { lt: "Asmens higiena",                 en: "Personal Care",         icon: "🧴" },
  "health":            { lt: "Sveikata",                       en: "Health & Wellness",     icon: "💊" },
  "ready-meals":       { lt: "Paruošti patiekalai",            en: "Ready Meals",           icon: "🍱" },
  "spices":            { lt: "Prieskoniai",                    en: "Spices & Seasonings",   icon: "🌶️" },
  "other":             { lt: "Kita",                           en: "Other",                 icon: "📦" },
};
